import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  var username = 'RITchie';
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Welcome&nbsp;
            <code className={styles.code}>{username}</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/smalllogo.webp"
                alt="Our Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/logo.webp"
            alt="Our Logo"
            width={300}
            height={300}
            priority
          />
        </div>

        <div className={styles.grid}>
        <a
            href="/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            {/* <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p> */}
          </a>
        <Link href="/addtask" className={styles.card}>
            <h2>
              Add Task <span>-&gt;</span>
            </h2>
            <p>
              To add new study target.
            </p>
          </Link>

         <Link href="/calendar" className={styles.card}>
            
              <h2>
                View Calendar <span>-&gt;</span>
              </h2>
              <p>
                View your Study Schedule!
              </p>
          </Link>

          <a
            href="/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            {/* <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p> */}
          </a>
        </div>
      </main>
    </>
  );
}
